### ISSUE TITLE
How about adding mode classffied by each distination, for example, LAN/Internet mode?

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#124]
I am using raspberry pi for sqm qos and proxy.
I should divide bandwidth limit setting for inside lan and internet.
For example,100Mbps lan and 1Mbps internet , and  these are classfied by htb.

**Comment by micron10** [comment]
if any write classffied  to cake i whan to try !


На ср, 1.01.2020 г. в 19:05 yutayu <notifications@github.com> написа:

**Comment by chromi** [comment]
> On 1 Jan, 2020, at 7:05 pm, yutayu <notifications@github.com> wrote:
> 
> I am using raspberry pi for sqm qos and proxy.
> I should divide bandwidth limit setting for inside lan and internet.
> For example,100Mbps lan and 1Mbps internet , and these are classfied by htb.

You should be able to use the same classifier filters with DRR instead of HTB, and attach distinct Cake instances to the resulting DRR leaves.  You can then set whichever bandwidth values and other parameters you like on each Cake instance.  This doesn't require adding any extra features to Cake itself.

Normally you would prefer to have separate physical interfaces for this type of application, one facing the Internet and one facing the LAN, so that all traffic between the two passes through both interfaces.  This is what Cake is designed to expect, and what the sqm-scripts package for OpenWRT helps you set up.  You can add a second Ethernet port to a Raspberry Pi on a USB dongle.

 - Jonathan Morton

**Comment by yutayu** [comment]
okay.
I got cake plan.

**Comment by yutayu** [comment]
At last , I set pi as router. Thanks :)
