### ISSUE TITLE
cake classes

### ISSUE THREAD

**Issue by dim-geo** [dtaht/sch_cake#14]
Hi,
is it feasible to access cake's classes using tc filter?
I want to set dscp bit on ingress but this is not feasible, so an alternative would be to access cake's classes so I classify donwstream properly.

**Comment by chromi** [comment]
Cake doesn't expose its classes or classification mechanism to the rest of
the qdisc hierarchy.  This helps it to be efficient, which is important on
consumer-grade routers.

It may however be feasible to add a DSCP marking filter as a qdisc, so that
packets pass through it (without actually being queued there) before
reaching cake.  That will have to do, unless and until it becomes possible
to run firewall rules before ingress queuing.
- Jonathan Morton

**Comment by dim-geo** [comment]
Is there such DSCP-marking qdisc?
Maybe it could become another layer in cake....
