### ISSUE TITLE
request : able to add leaf qdisc under cake

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#150]
I use tbf qdisc + fq qdisc.
But it takes latency.
I wanted to use fq with cake.

**Comment by yutayu** [comment]
tc qdisc add dev eth0 root handle 1: stab linklayer atm overhead -4 tbf rate 840kbit latency 300ms burst 1696
tc qdisc add dev eth0 parent 1:  fq limit 1000

like this.

**Comment by chromi** [comment]
> On 21 May, 2021, at 2:10 pm, yutayu ***@***.***> wrote:
> 
> tc qdisc add dev eth0 root handle 1: stab linklayer atm overhead -4 tbf rate 840kbit latency 300ms burst 1696
> tc qdisc add dev eth0 parent 1: fq limit 1000

Replace both these lines with:

tc qdisc add dev eth0 root handle 1: cake bandwidth 840kbit flows atm overhead 10

You will not need the FQ qdisc, because Cake includes a good FQ implementation.  You will not need TBF or STAB, because Cake's shaper does a better job of shaping than TBF and includes the overhead compensation features that you're using from STAB.  Cake's "overhead" parameter is specified relative to the Layer 3 IP packet which is what actually gets encapsulated in most alternative link layers, whereas STAB specifies relative to a Layer 2 Ethernet packet.

 - Jonathan Morton

**Comment by yutayu** [comment]
@chromi 
Shame on me.
Thanks a lot : )
