### ISSUE TITLE
cake_set_rate set to target twice in diffserv_llt

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#41]
Was this intentional?

	cake_set_rate(&q->tins[2], rate, mtu,
		      US2TIME(q->target), US2TIME(q->target));

**Comment by chromi** [comment]
> On 23 Dec, 2016, at 02:20, Dave Täht <notifications@github.com> wrote:
> 
> Was this intentional?
> 
> cake_set_rate(&q->tins[2], rate, mtu,
> 	      US2TIME(q->target), US2TIME(q->target));

Yes.  This makes Codel and BLUE more aggressive in the tin intended for latency-sensitive traffic; they respond sooner and ramp up faster.  Since that tin isn’t meant for bulk traffic, the effect on sustained throughput isn’t important.

You’ll notice I’ve done the same in diffserv3.

 - Jonathan Morton

**Comment by dtaht** [comment]
I confess to being very dubious. What sorts of latency sensitive traffic have you tested?

**Comment by dtaht** [comment]
I totally didn't beieve in this idea, so I reverted it. I'd be glad to try it again, once we have a test that coud show a difference here.
