### ISSUE TITLE
ethernet option and mpu

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#48]
I have no idea what the new ethernet option is supposed to be doing... it sets mpu to 84??
 And overhead??

root@dancer:~/git/sch_cake# tc qdisc show dev eno1
qdisc cake 8008: root refcnt 2 bandwidth 100Mbit diffserv3 triple-isolate rtt 100.0ms noatm overhead 38 via-ethernet mpu 84

**Comment by dtaht** [comment]
what's the difference between the default mode and "ethernet"?

**Comment by moeller0** [comment]
Hi Dave,


> On Jan 27, 2017, at 23:27, Dave Täht <notifications@github.com> wrote:
> 
> I have no idea what the new ethernet option is supposed to be doing... it sets mpu to 84??
> And overhead??

According to https://en.wikipedia.org/wiki/Ethernet_frame a layer1 frame plus the inter packet gap (IPG)  correspond to 72 + 12 bytes worth of transfer time. Or put differently Preamble (7) Start of Frame delimiter (1) and IPG (12) add 20 more bytes to the overhead. And 18 (srcMAC dstMAC, ethertype and FCS) bytes plus 20 equals 38. Now why is that correct, because as far as I can tell ethernet is specified in L1 bit capacity, so one truly needs to add these if for example one wants to shape a Gbit ethernet link to rates a 100Mbit ethernet can transfer without buffering. With ethernet’s minimal L2 frame being 64 byte adding the missing 20 leads to 84 bytes MPU. For all I can tell this, while looking unusual, this seems to be correct. I want to add that this most likely only crops up as an issue if one shapes close to the maximum speed of an ethernet link, and/or only use minimally small packets. (I also had no input on that tc change, so I am not defending my own actions/decisions here).

Best Regards
	Sebastian

**Comment by dtaht** [comment]
So we should be doing way more measurements with very small packets than we have. But....
why overhead 38 AND mpu 84? and  10GigE is different..... and.... agghhh.... well I loved the result some got on docsis, now I gotta go think about it.

**Comment by moeller0** [comment]
Hi Dave,

> On Jan 27, 2017, at 23:46, Dave Täht <notifications@github.com> wrote:
> 
> So we should be doing way more measurements with very small packets than we have. But....
> why overhead 38 AND mpu 84?

Good question, I have not looked into the code. Depending on where mpu is brought into the mix this makes sense, if we first add the overhead and then do max(payload+overhead, mpu) the existing system makes sense. The overhead is corrct with 38, because Preamble, SFD and IPG are added to each frame independent of size.


> and 10GigE is different…..

	I have not looked there, is it really different?

> and.... agghhh.... well I loved the result some got on docsis, now I gotta go think about it.

	According to the docsis specs the docsis shaper that sets a users speed really only adds srcMAC, dstMAC, ethertype, and FCS, so the other 20 bytes are irrelevant for DOCSIS (if uncongested one gets L2 rates, if congested it does not really matter anymore). Whether docisis maintains the L2-mpu of 64 bytes I am not sure, I would guess yes (VDSL allows shorter frames but that is explicitly mentioned in the relevant ITU standards and it is not clear whether anybody actually does that, since it would require either dropping the FCS and recaclulating it at the end of the vdsl link or recalculating it for the changed payload. At least if wikipedia is correct in that the padding will be included in the FCS). Whether or not that is a problem for existing data really depends on the packet size mix (on my vdsl link the only packets below l2 64B are ppp management frames, that are a) rare and b) invisible to the shaper on pppoe-wan anyway so one still needs to keep space for some unexpected packets...)

Best Regards
	Sebastian

**Comment by ldir-EDB0** [comment]
I *think* that when you were looking at this you had a mismatch between cake and tc version - ie an API gotcha - or maybe not.  But I certainly don't see this and I know I'm looking at latest cake head and a matching iproute2/tc patch.

The ETHERNET parameter in the api, AFAIKT is a flag to cake to override it's knowledge of linux's packet overheads with its own.  Its a modifier as to how to interpret the OVERHEAD parameter.

The ETHERNET parameter is also returned from cake to tc and represents the amount of compensation that linux knows about....it's returned to tc and any positive value is indicated as as 'via-ethernet' psuedo-parameter.  

 I do wonder if the actual value returned should be indicated.

RANT
It would be a *really good idea* if as part of these tests some sort of clue/indication with regard to version/branch/tree whatever of cake & tc was being used when (potential) issues are raised.  A number of questions raised could also be answered by looking at the code...tc has some nice comments in it regarding the ETHERNET parameter.  Of course the trick there is knowing which commit for cake and tc is being used.....for lede a look at package/kernel/kmod-sched-cake/Makefile & package/network/utils/iproute2/patches/950-add-cake-to-tc.patch  should be fairly definitive.
/RANT
