### ISSUE TITLE
question about diffserv4 tin thresholds

### ISSUE THREAD

**Issue by commodo** [dtaht/sch_cake#61]
Specifically this commit:
https://github.com/dtaht/sch_cake/commit/423112ed57ad5d237ef90074f3651340d7ae6415

I set QoS with   "tc qdisc replace dev eth1 root cake diffserv4 flows
bandwidth 100mbit"

In an older version of Cake:
`------------------------------------------------`
capacity estimate: 100Mbit
Tin 0 Tin 1 Tin 2 Tin 3
thresh 100Mbit 93750Kbit 75Mbit 25Mbit
target 5.0ms 5.0ms 5.0ms 5.0ms
interval 100.0ms 100.0ms 100.0ms 100.0ms
`------------------------------------------------`

and with the more recent one:
`------------------------------------------------`
capacity estimate: 100Mbit
Bulk Best Effort Video Voice
thresh 6250Kbit 100Mbit 50Mbit 25Mbit
target 5.0ms 5.0ms 5.0ms 5.0ms
interval 100.0ms 100.0ms 100.0ms 100.0ms
`------------------------------------------------`

The questions:
- why did tin2 threshold reduce from 75% to 50% ?
- why did tin1 threshold change from 15/16 to 100% ?
- i'm assuming that tin0's may be residual 1/16 of 100 mbit ? ; maybe
tin1 should show 15/16 of 100mbit ?

It may be a reporting issue, or not.
I'm trying to understand the change, and how to handle it internally :)
But, the current situation does not match what's mentioned here:
https://www.bufferbloat.net/projects/codel/wiki/CakeTechnical/#priority-queue

Thanks
Alex

**Comment by chromi** [comment]
The reason for the change was that the internal algorithm used for tin
selection on dequeue changed quite fundamentally.  It has since changed
again!  The new algorithm isn't documented on CakeTechnical, but a revised
set of documentation is on the way.

- Jonathan Morton

On 19 Jul 2017 14:51, "Alexandru Ardelean" <notifications@github.com> wrote:

Specifically this commit:
423112e
<https://github.com/dtaht/sch_cake/commit/423112ed57ad5d237ef90074f3651340d7ae6415>

I set QoS with "tc qdisc replace dev eth1 root cake diffserv4 flows
bandwidth 100mbit"
In an older version of Cake: capacity estimate: 100Mbit
Tin 0 Tin 1 Tin 2 Tin 3
thresh 100Mbit 93750Kbit 75Mbit 25Mbit
target 5.0ms 5.0ms 5.0ms 5.0ms
interval 100.0ms 100.0ms 100.0ms 100.0ms and with the more recent one: capacity
estimate: 100Mbit
Bulk Best Effort Video Voice
thresh 6250Kbit 100Mbit 50Mbit 25Mbit
target 5.0ms 5.0ms 5.0ms 5.0ms
interval 100.0ms 100.0ms 100.0ms 100.0ms

The questions:

   - why did tin2 threshold reduce from 75% to 50% ?
   - why did tin1 threshold change from 15/16 to 100% ?
   - i'm assuming that tin0's may be residual 1/16 of 100 mbit ? ; maybe
   tin1 should show 15/16 of 100mbit ?

It may be a reporting issue, or not.
I'm trying to understand the change, and how to handle it internally :)
But, the current situation does not match what's mentioned here:
https://www.bufferbloat.net/projects/codel/wiki/
CakeTechnical/#priority-queue

Thanks
Alex

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dtaht/sch_cake/issues/61>, or mute the thread

**Comment by commodo** [comment]
cool
thanks
